#!/bin/bash

echo "📋 Backend Deployment Instructions for Google Cloud Run"
echo "======================================================"
echo ""
echo "1️⃣  First, authenticate with Google Cloud:"
echo "   gcloud auth login"
echo ""
echo "2️⃣  Set your project:"
echo "   gcloud config set project parentload-ba995"
echo ""
echo "3️⃣  Navigate to the server directory:"
echo "   cd server"
echo ""
echo "4️⃣  Deploy to Cloud Run (this will build and deploy using the Dockerfile):"
echo "   gcloud run deploy parentload-backend \\"
echo "     --source . \\"
echo "     --region us-central1 \\"
echo "     --platform managed \\"
echo "     --allow-unauthenticated \\"
echo "     --port 8080 \\"
echo "     --memory 512Mi"
echo ""
echo "5️⃣  After deployment, set environment variables in Cloud Console:"
echo "   - Go to: https://console.cloud.google.com/run"
echo "   - Click on 'parentload-backend'"
echo "   - Click 'Edit & Deploy New Revision'"
echo "   - Go to 'Variables & Secrets' tab"
echo "   - Add these environment variables:"
echo "     • SENDGRID_API_KEY (your SendGrid API key)"
echo "     • SENDGRID_FROM_EMAIL=hello@allie.family"
echo "     • TWILIO_ACCOUNT_SID (if using SMS)"
echo "     • TWILIO_AUTH_TOKEN (if using SMS)"
echo "     • TWILIO_PHONE_NUMBER (if using SMS)"
echo "     • ANTHROPIC_API_KEY (if using Claude)"
echo "     • ANTHROPIC_SALES_API_KEY (for sales chat)"
echo "     • FRONTEND_URL=https://checkallie.com"
echo ""
echo "6️⃣  After deployment, update your frontend:"
echo "   - Note the service URL from Cloud Run"
echo "   - Create/update .env.production:"
echo "     REACT_APP_BACKEND_URL=https://[your-service-url]"
echo "   - Rebuild and deploy:"
echo "     npm run build && firebase deploy --only hosting"
echo ""
echo "🎯 That's it! Your backend will be live and emails will use the new templates."