#!/bin/bash

echo "🚀 Setting up Calendar Integration for Allie"
echo "========================================"
echo ""

echo "📋 Step 1: Create Firebase Indexes"
echo "You need to create these indexes manually in Firebase Console:"
echo ""
echo "🔗 Events Index:"
echo "https://console.firebase.google.com/v1/r/project/parentload-ba995/firestore/indexes?create_composite=Ck9wcm9qZWN0cy9wYXJlbnRsb2FkLWJhOTk1L2RhdGFiYXNlcy8oZGVmYXVsdCkvY29sbGVjdGlvbkdyb3Vwcy9ldmVudHMvaW5kZXhlcy9fEAEaDAoIZmFtaWx5SWQQARoKCgZzdGF0dXMQARoNCglzdGFydFRpbWUQAhoMCghfX25hbWVfXxAC"
echo ""
echo "🔗 Processed Emails Index:"
echo "https://console.firebase.google.com/v1/r/project/parentload-ba995/firestore/indexes?create_composite=Cllwcm9qZWN0cy9wYXJlbnRsb2FkLWJhOTk1L2RhdGFiYXNlcy8oZGVmYXVsdCkvY29sbGVjdGlvbkdyb3Vwcy9wcm9jZXNzZWRfZW1haWxzL2luZGV4ZXMvXxABGgwKCGZhbWlseUlkEAEaDwoLcHJvY2Vzc2VkQXQQAhoMCghfX25hbWVfXxAC"
echo ""
echo "📋 Step 2: Configure OAuth Credentials"
echo ""
echo "For Google Calendar:"
echo "1. Go to: https://console.cloud.google.com/"
echo "2. Enable Google Calendar API"  
echo "3. Create OAuth 2.0 Client ID"
echo "4. Set environment variables:"
echo "   REACT_APP_GOOGLE_CLIENT_ID=your-client-id.apps.googleusercontent.com"
echo "   REACT_APP_GOOGLE_API_KEY=your-api-key"
echo ""
echo "For Outlook Calendar:"
echo "1. Go to: https://portal.azure.com/"
echo "2. Create App Registration"
echo "3. Add Calendars.ReadWrite permission"
echo "4. Set environment variable:"
echo "   REACT_APP_OUTLOOK_CLIENT_ID=your-outlook-client-id"
echo ""
echo "📋 Step 3: Restart Development Server"
echo "After setting environment variables, restart with:"
echo "npm start"
echo ""
echo "✅ Features Enabled:"
echo "• One-click Google Calendar connection"
echo "• One-click Outlook Calendar connection"  
echo "• Full calendar access (read, write, delete events)"
echo "• Two-way sync between Allie and external calendars"
echo "• Visual connection status and error handling"
echo ""
echo "📖 See CALENDAR_OAUTH_SETUP.md for detailed setup instructions"